

riotAPIKey = "";

summoner = "";
summonerGetInfoPrefix = "https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-name/";


challengeGetInfoPrefix = "https://na1.api.riotgames.com/lol/challenges/v1/player-data/";

apiKeySuffix = "?api_key=";

jQuery.getJSON(
summonerGetInfoPrefix + summoner + apiKeySuffix + riotAPIKey, 
function(data){
    console.log(data);
    console.log(data.name);
    var name = data.name;


    var summonerPUUID = data.puuid;

    jQuery.getJSON(
    challengeGetInfoPrefix + summonerPUUID + apiKeySuffix + riotAPIKey,
    function(challenge){
        console.log(challenge);
        console.log(challenge.challenges[0]);
        console.log(challenge.challenges[0].level);
        jQuery(".challenge0level").append(challenge.challenges[0].level);
        jQuery(".challenge1level").append(challenge.challenges[1].level);
        jQuery(".challenge2level").append(challenge.challenges[2].level);
        jQuery(".challenge3level").append(challenge.challenges[3].level);
        jQuery(".challenge4level").append(challenge.challenges[4].level);
        jQuery(".challenge5level").append(challenge.challenges[5].level);
        jQuery(".challenge6level").append(challenge.challenges[6].level);
        jQuery(".challenge7level").append(challenge.challenges[7].level);
        jQuery(".challenge8level").append(challenge.challenges[8].level);
        jQuery(".challenge9level").append(challenge.challenges[9].level);
        jQuery(".challenge10level").append(challenge.challenges[10].level);
        jQuery(".challenge11level").append(challenge.challenges[11].level);
        jQuery(".challenge12level").append(challenge.challenges[12].level);
        jQuery(".challenge13level").append(challenge.challenges[13].level);
        jQuery(".challenge14level").append(challenge.challenges[14].level);
        jQuery(".challenge15level").append(challenge.challenges[15].level);
        jQuery(".challenge16level").append(challenge.challenges[16].level);
        jQuery(".challenge17level").append(challenge.challenges[17].level);
        jQuery(".challenge18level").append(challenge.challenges[18].level);
        jQuery(".challenge19level").append(challenge.challenges[19].level);
        jQuery(".challenge20level").append(challenge.challenges[20].level);
        jQuery(".challenge21level").append(challenge.challenges[21].level);
        jQuery(".challenge22level").append(challenge.challenges[22].level);
        jQuery(".challenge23level").append(challenge.challenges[23].level);
        jQuery(".challenge24level").append(challenge.challenges[24].level);
        jQuery(".challenge25level").append(challenge.challenges[25].level);
        jQuery(".challenge26level").append(challenge.challenges[26].level);
        jQuery(".challenge27level").append(challenge.challenges[27].level);
        jQuery(".challenge28level").append(challenge.challenges[28].level);
        jQuery(".challenge29level").append(challenge.challenges[29].level);
        jQuery(".challenge30level").append(challenge.challenges[30].level);
        jQuery(".challenge31level").append(challenge.challenges[31].level);
        jQuery(".challenge32level").append(challenge.challenges[32].level);
        jQuery(".challenge33level").append(challenge.challenges[33].level);
        jQuery(".challenge34level").append(challenge.challenges[34].level);
        jQuery(".challenge35level").append(challenge.challenges[35].level);
        jQuery(".challenge36level").append(challenge.challenges[36].level);
        jQuery(".challenge37level").append(challenge.challenges[37].level);
        jQuery(".challenge38level").append(challenge.challenges[38].level);
        jQuery(".challenge39level").append(challenge.challenges[39].level);
        jQuery(".challenge40level").append(challenge.challenges[40].level);
        jQuery(".challenge41level").append(challenge.challenges[41].level);
        jQuery(".challenge42level").append(challenge.challenges[42].level);
        jQuery(".challenge43level").append(challenge.challenges[43].level);
        jQuery(".challenge44level").append(challenge.challenges[44].level);
        jQuery(".challenge45level").append(challenge.challenges[45].level);
        jQuery(".challenge46level").append(challenge.challenges[46].level);
        jQuery(".challenge47level").append(challenge.challenges[47].level);
        jQuery(".challenge48level").append(challenge.challenges[48].level);
        jQuery(".challenge49level").append(challenge.challenges[49].level);
        jQuery(".challenge50level").append(challenge.challenges[50].level);
        jQuery(".challenge51level").append(challenge.challenges[51].level);
        jQuery(".challenge52level").append(challenge.challenges[52].level);
        jQuery(".challenge53level").append(challenge.challenges[53].level);
        jQuery(".challenge54level").append(challenge.challenges[54].level);
        jQuery(".challenge55level").append(challenge.challenges[55].level);
        jQuery(".challenge56level").append(challenge.challenges[56].level);
        jQuery(".challenge57level").append(challenge.challenges[57].level);
        jQuery(".challenge58level").append(challenge.challenges[58].level);
        jQuery(".challenge59level").append(challenge.challenges[59].level);
        jQuery(".challenge60level").append(challenge.challenges[60].level);
        jQuery(".challenge61level").append(challenge.challenges[61].level);
        jQuery(".challenge62level").append(challenge.challenges[62].level);
        jQuery(".challenge63level").append(challenge.challenges[63].level);
        jQuery(".challenge64level").append(challenge.challenges[64].level);
        jQuery(".challenge65level").append(challenge.challenges[65].level);
        jQuery(".challenge66level").append(challenge.challenges[66].level);
        jQuery(".challenge67level").append(challenge.challenges[67].level);
        jQuery(".challenge68level").append(challenge.challenges[68].level);
        jQuery(".challenge69level").append(challenge.challenges[69].level);
        jQuery(".challenge70level").append(challenge.challenges[70].level);
        jQuery(".challenge71level").append(challenge.challenges[71].level);
        jQuery(".challenge72level").append(challenge.challenges[72].level);
        jQuery(".challenge73level").append(challenge.challenges[73].level);
        jQuery(".challenge74level").append(challenge.challenges[74].level);
        jQuery(".challenge75level").append(challenge.challenges[75].level);
        jQuery(".challenge76level").append(challenge.challenges[76].level);
        jQuery(".challenge77level").append(challenge.challenges[77].level);
        jQuery(".challenge78level").append(challenge.challenges[78].level);
        jQuery(".challenge79level").append(challenge.challenges[79].level);
        jQuery(".challenge80level").append(challenge.challenges[80].level);
        jQuery(".challenge81level").append(challenge.challenges[81].level);
        jQuery(".challenge82level").append(challenge.challenges[82].level);
        jQuery(".challenge83level").append(challenge.challenges[83].level);
        jQuery(".challenge84level").append(challenge.challenges[84].level);
        jQuery(".challenge85level").append(challenge.challenges[85].level);
        jQuery(".challenge86level").append(challenge.challenges[86].level);
        jQuery(".challenge87level").append(challenge.challenges[87].level);
        jQuery(".challenge88level").append(challenge.challenges[88].level);
        jQuery(".challenge89level").append(challenge.challenges[89].level);
        jQuery(".challenge90level").append(challenge.challenges[90].level);
        jQuery(".challenge91level").append(challenge.challenges[91].level);
        jQuery(".challenge92level").append(challenge.challenges[92].level);
        jQuery(".challenge93level").append(challenge.challenges[93].level);
        jQuery(".challenge94level").append(challenge.challenges[94].level);
        jQuery(".challenge95level").append(challenge.challenges[95].level);
        jQuery(".challenge96level").append(challenge.challenges[96].level);
        jQuery(".challenge97level").append(challenge.challenges[97].level);
        jQuery(".challenge98level").append(challenge.challenges[98].level);
        jQuery(".challenge99level").append(challenge.challenges[99].level);
        jQuery(".challenge100level").append(challenge.challenges[100].level);
        jQuery(".challenge101level").append(challenge.challenges[101].level);
        jQuery(".challenge102level").append(challenge.challenges[102].level);
        jQuery(".challenge103level").append(challenge.challenges[103].level);
        jQuery(".challenge104level").append(challenge.challenges[104].level);
        jQuery(".challenge105level").append(challenge.challenges[105].level);
        jQuery(".challenge106level").append(challenge.challenges[106].level);
        jQuery(".challenge107level").append(challenge.challenges[107].level);
        jQuery(".challenge108level").append(challenge.challenges[108].level);
        jQuery(".challenge109level").append(challenge.challenges[109].level);
        jQuery(".challenge110level").append(challenge.challenges[110].level);
        jQuery(".challenge111level").append(challenge.challenges[111].level);
        jQuery(".challenge112level").append(challenge.challenges[112].level);
        jQuery(".challenge113level").append(challenge.challenges[113].level);
        jQuery(".challenge114level").append(challenge.challenges[114].level);
        jQuery(".challenge115level").append(challenge.challenges[115].level);
        jQuery(".challenge116level").append(challenge.challenges[116].level);
        jQuery(".challenge117level").append(challenge.challenges[117].level);
        jQuery(".challenge118level").append(challenge.challenges[118].level);
        jQuery(".challenge119level").append(challenge.challenges[119].level);
        jQuery(".challenge120level").append(challenge.challenges[120].level);
        jQuery(".challenge121level").append(challenge.challenges[121].level);
        jQuery(".challenge122level").append(challenge.challenges[122].level);
        jQuery(".challenge123level").append(challenge.challenges[123].level);
        jQuery(".challenge124level").append(challenge.challenges[124].level);
        jQuery(".challenge125level").append(challenge.challenges[125].level);
        jQuery(".challenge126level").append(challenge.challenges[126].level);
        jQuery(".challenge127level").append(challenge.challenges[127].level);
        jQuery(".challenge128level").append(challenge.challenges[128].level);
        jQuery(".challenge129level").append(challenge.challenges[129].level);
        jQuery(".challenge130level").append(challenge.challenges[130].level);
        jQuery(".challenge131level").append(challenge.challenges[131].level);
        jQuery(".challenge132level").append(challenge.challenges[132].level);
        jQuery(".challenge133level").append(challenge.challenges[133].level);
        jQuery(".challenge134level").append(challenge.challenges[134].level);
        jQuery(".challenge135level").append(challenge.challenges[135].level);
        jQuery(".challenge136level").append(challenge.challenges[136].level);
        jQuery(".challenge137level").append(challenge.challenges[137].level);
        jQuery(".challenge138level").append(challenge.challenges[138].level);
        jQuery(".challenge139level").append(challenge.challenges[139].level);
        jQuery(".challenge140level").append(challenge.challenges[140].level);
        jQuery(".challenge141level").append(challenge.challenges[141].level);
        jQuery(".challenge142level").append(challenge.challenges[142].level);
        jQuery(".challenge143level").append(challenge.challenges[143].level);
        jQuery(".challenge144level").append(challenge.challenges[144].level);
        jQuery(".challenge145level").append(challenge.challenges[145].level);
        jQuery(".challenge146level").append(challenge.challenges[146].level);
        jQuery(".challenge147level").append(challenge.challenges[147].level);
        jQuery(".challenge148level").append(challenge.challenges[148].level);
        jQuery(".challenge149level").append(challenge.challenges[149].level);
        jQuery(".challenge150level").append(challenge.challenges[150].level);
        jQuery(".challenge151level").append(challenge.challenges[151].level);
        jQuery(".challenge152level").append(challenge.challenges[152].level);
        jQuery(".challenge153level").append(challenge.challenges[153].level);
        jQuery(".challenge154level").append(challenge.challenges[154].level);
        jQuery(".challenge155level").append(challenge.challenges[155].level);
        jQuery(".challenge156level").append(challenge.challenges[156].level);
        jQuery(".challenge157level").append(challenge.challenges[157].level);
        jQuery(".challenge158level").append(challenge.challenges[158].level);
        jQuery(".challenge159level").append(challenge.challenges[159].level);
        jQuery(".challenge160level").append(challenge.challenges[160].level);
        jQuery(".challenge161level").append(challenge.challenges[161].level);
        jQuery(".challenge162level").append(challenge.challenges[162].level);
        jQuery(".challenge163level").append(challenge.challenges[163].level);
        jQuery(".challenge164level").append(challenge.challenges[164].level);
        jQuery(".challenge165level").append(challenge.challenges[165].level);
        jQuery(".challenge166level").append(challenge.challenges[166].level);
        jQuery(".challenge167level").append(challenge.challenges[167].level);
        jQuery(".challenge168level").append(challenge.challenges[168].level);
        jQuery(".challenge169level").append(challenge.challenges[169].level);
        jQuery(".challenge170level").append(challenge.challenges[170].level);
        jQuery(".challenge171level").append(challenge.challenges[171].level);
        jQuery(".challenge172level").append(challenge.challenges[172].level);
        jQuery(".challenge173level").append(challenge.challenges[173].level);
        jQuery(".challenge174level").append(challenge.challenges[174].level);
        jQuery(".challenge175level").append(challenge.challenges[175].level);
        jQuery(".challenge176level").append(challenge.challenges[176].level);
        jQuery(".challenge177level").append(challenge.challenges[177].level);
        jQuery(".challenge178level").append(challenge.challenges[178].level);
        jQuery(".challenge179level").append(challenge.challenges[179].level);
        jQuery(".challenge180level").append(challenge.challenges[180].level);
        jQuery(".challenge181level").append(challenge.challenges[181].level);
        jQuery(".challenge182level").append(challenge.challenges[182].level);
        jQuery(".challenge183level").append(challenge.challenges[183].level);
        jQuery(".challenge184level").append(challenge.challenges[184].level);
        jQuery(".challenge185level").append(challenge.challenges[185].level);
        jQuery(".challenge186level").append(challenge.challenges[186].level);
        jQuery(".challenge187level").append(challenge.challenges[187].level);
        jQuery(".challenge188level").append(challenge.challenges[188].level);
        jQuery(".challenge189level").append(challenge.challenges[189].level);
        jQuery(".challenge190level").append(challenge.challenges[190].level);
        jQuery(".challenge191level").append(challenge.challenges[191].level);
        jQuery(".challenge192level").append(challenge.challenges[192].level);
        jQuery(".challenge193level").append(challenge.challenges[193].level);
        jQuery(".challenge194level").append(challenge.challenges[194].level);
        jQuery(".challenge195level").append(challenge.challenges[195].level);
        jQuery(".challenge196level").append(challenge.challenges[196].level);
        jQuery(".challenge197level").append(challenge.challenges[197].level);
        jQuery(".challenge198level").append(challenge.challenges[198].level);
        jQuery(".challenge199level").append(challenge.challenges[199].level);
        jQuery(".challenge200level").append(challenge.challenges[200].level);
        jQuery(".challenge201level").append(challenge.challenges[201].level);
        jQuery(".challenge202level").append(challenge.challenges[202].level);
        jQuery(".challenge203level").append(challenge.challenges[203].level);
        jQuery(".challenge204level").append(challenge.challenges[204].level);
        jQuery(".challenge205level").append(challenge.challenges[205].level);
        jQuery(".challenge206level").append(challenge.challenges[206].level);
        jQuery(".challenge207level").append(challenge.challenges[207].level);
        jQuery(".challenge208level").append(challenge.challenges[208].level);
        jQuery(".challenge209level").append(challenge.challenges[209].level);
        jQuery(".challenge210level").append(challenge.challenges[210].level);
        jQuery(".challenge211level").append(challenge.challenges[211].level);
        jQuery(".challenge212level").append(challenge.challenges[212].level);
        jQuery(".challenge213level").append(challenge.challenges[213].level);
        jQuery(".challenge214level").append(challenge.challenges[214].level);
        jQuery(".challenge215level").append(challenge.challenges[215].level);
        jQuery(".challenge216level").append(challenge.challenges[216].level);
        jQuery(".challenge217level").append(challenge.challenges[217].level);
        jQuery(".challenge218level").append(challenge.challenges[218].level);
        jQuery(".challenge219level").append(challenge.challenges[219].level);
        jQuery(".challenge220level").append(challenge.challenges[220].level);
        jQuery(".challenge221level").append(challenge.challenges[221].level);
        jQuery(".challenge222level").append(challenge.challenges[222].level);
        jQuery(".challenge223level").append(challenge.challenges[223].level);
        jQuery(".challenge224level").append(challenge.challenges[224].level);
        jQuery(".challenge225level").append(challenge.challenges[225].level);
        jQuery(".challenge226level").append(challenge.challenges[226].level);
        jQuery(".challenge227level").append(challenge.challenges[227].level);
        jQuery(".challenge228level").append(challenge.challenges[228].level);
        jQuery(".challenge229level").append(challenge.challenges[229].level);
        jQuery(".challenge230level").append(challenge.challenges[230].level);
        jQuery(".challenge231level").append(challenge.challenges[231].level);
        jQuery(".challenge232level").append(challenge.challenges[232].level);
        jQuery(".challenge233level").append(challenge.challenges[233].level);
        jQuery(".challenge234level").append(challenge.challenges[234].level);
        jQuery(".challenge235level").append(challenge.challenges[235].level);
        jQuery(".challenge236level").append(challenge.challenges[236].level);
        jQuery(".challenge237level").append(challenge.challenges[237].level);
        jQuery(".challenge238level").append(challenge.challenges[238].level);
        jQuery(".challenge239level").append(challenge.challenges[239].level);
        jQuery(".challenge240level").append(challenge.challenges[240].level);
        jQuery(".challenge241level").append(challenge.challenges[241].level);
        jQuery(".challenge242level").append(challenge.challenges[242].level);
        jQuery(".challenge243level").append(challenge.challenges[243].level);
        jQuery(".challenge244level").append(challenge.challenges[244].level);
        jQuery(".challenge245level").append(challenge.challenges[245].level);
        jQuery(".challenge246level").append(challenge.challenges[246].level);
        jQuery(".challenge247level").append(challenge.challenges[247].level);
        jQuery(".challenge248level").append(challenge.challenges[248].level);
        jQuery(".challenge249level").append(challenge.challenges[249].level);
        jQuery(".challenge250level").append(challenge.challenges[250].level);
        jQuery(".challenge251level").append(challenge.challenges[251].level);
        jQuery(".challenge252level").append(challenge.challenges[252].level);
        jQuery(".challenge253level").append(challenge.challenges[253].level);
        jQuery(".challenge254level").append(challenge.challenges[254].level);
        jQuery(".challenge255level").append(challenge.challenges[255].level);
        jQuery(".challenge256level").append(challenge.challenges[256].level);
        jQuery(".challenge257level").append(challenge.challenges[257].level);
        //percentile
        jQuery(".challenge0percentile").append(Math.floor(challenge.challenges[0].percentile * 1000) / 10.0);
        jQuery(".challenge1percentile").append(Math.floor(challenge.challenges[1].percentile * 1000) / 10.0);
        jQuery(".challenge2percentile").append(Math.floor(challenge.challenges[2].percentile * 1000) / 10.0);
        jQuery(".challenge3percentile").append(Math.floor(challenge.challenges[3].percentile * 1000) / 10.0);
        jQuery(".challenge4percentile").append(Math.floor(challenge.challenges[4].percentile * 1000) / 10.0);
        jQuery(".challenge5percentile").append(Math.floor(challenge.challenges[5].percentile * 1000) / 10.0);
        jQuery(".challenge6percentile").append(Math.floor(challenge.challenges[6].percentile * 1000) / 10.0);
        jQuery(".challenge7percentile").append(Math.floor(challenge.challenges[7].percentile * 1000) / 10.0);
        jQuery(".challenge8percentile").append(Math.floor(challenge.challenges[8].percentile * 1000) / 10.0);
        jQuery(".challenge9percentile").append(Math.floor(challenge.challenges[9].percentile * 1000) / 10.0);
        jQuery(".challenge10percentile").append(Math.floor(challenge.challenges[10].percentile * 1000) / 10.0);
        jQuery(".challenge11percentile").append(Math.floor(challenge.challenges[11].percentile * 1000) / 10.0);
        jQuery(".challenge12percentile").append(Math.floor(challenge.challenges[12].percentile * 1000) / 10.0);
        jQuery(".challenge13percentile").append(Math.floor(challenge.challenges[13].percentile * 1000) / 10.0);
        jQuery(".challenge14percentile").append(Math.floor(challenge.challenges[14].percentile * 1000) / 10.0);
        jQuery(".challenge15percentile").append(Math.floor(challenge.challenges[15].percentile * 1000) / 10.0);
        jQuery(".challenge16percentile").append(Math.floor(challenge.challenges[16].percentile * 1000) / 10.0);
        jQuery(".challenge17percentile").append(Math.floor(challenge.challenges[17].percentile * 1000) / 10.0);
        jQuery(".challenge18percentile").append(Math.floor(challenge.challenges[18].percentile * 1000) / 10.0);
        jQuery(".challenge19percentile").append(Math.floor(challenge.challenges[19].percentile * 1000) / 10.0);
        jQuery(".challenge20percentile").append(Math.floor(challenge.challenges[20].percentile * 1000) / 10.0);
        jQuery(".challenge21percentile").append(Math.floor(challenge.challenges[21].percentile * 1000) / 10.0);
        jQuery(".challenge22percentile").append(Math.floor(challenge.challenges[22].percentile * 1000) / 10.0);
        jQuery(".challenge23percentile").append(Math.floor(challenge.challenges[23].percentile * 1000) / 10.0);
        jQuery(".challenge24percentile").append(Math.floor(challenge.challenges[24].percentile * 1000) / 10.0);
        jQuery(".challenge25percentile").append(Math.floor(challenge.challenges[25].percentile * 1000) / 10.0);
        jQuery(".challenge26percentile").append(Math.floor(challenge.challenges[26].percentile * 1000) / 10.0);
        jQuery(".challenge27percentile").append(Math.floor(challenge.challenges[27].percentile * 1000) / 10.0);
        jQuery(".challenge28percentile").append(Math.floor(challenge.challenges[28].percentile * 1000) / 10.0);
        jQuery(".challenge29percentile").append(Math.floor(challenge.challenges[29].percentile * 1000) / 10.0);
        jQuery(".challenge30percentile").append(Math.floor(challenge.challenges[30].percentile * 1000) / 10.0);
        jQuery(".challenge31percentile").append(Math.floor(challenge.challenges[31].percentile * 1000) / 10.0);
        jQuery(".challenge32percentile").append(Math.floor(challenge.challenges[32].percentile * 1000) / 10.0);
        jQuery(".challenge33percentile").append(Math.floor(challenge.challenges[33].percentile * 1000) / 10.0);
        jQuery(".challenge34percentile").append(Math.floor(challenge.challenges[34].percentile * 1000) / 10.0);
        jQuery(".challenge35percentile").append(Math.floor(challenge.challenges[35].percentile * 1000) / 10.0);
        jQuery(".challenge36percentile").append(Math.floor(challenge.challenges[36].percentile * 1000) / 10.0);
        jQuery(".challenge37percentile").append(Math.floor(challenge.challenges[37].percentile * 1000) / 10.0);
        jQuery(".challenge38percentile").append(Math.floor(challenge.challenges[38].percentile * 1000) / 10.0);
        jQuery(".challenge39percentile").append(Math.floor(challenge.challenges[39].percentile * 1000) / 10.0);
        jQuery(".challenge40percentile").append(Math.floor(challenge.challenges[40].percentile * 1000) / 10.0);
        jQuery(".challenge41percentile").append(Math.floor(challenge.challenges[41].percentile * 1000) / 10.0);
        jQuery(".challenge42percentile").append(Math.floor(challenge.challenges[42].percentile * 1000) / 10.0);
        jQuery(".challenge43percentile").append(Math.floor(challenge.challenges[43].percentile * 1000) / 10.0);
        jQuery(".challenge44percentile").append(Math.floor(challenge.challenges[44].percentile * 1000) / 10.0);
        jQuery(".challenge45percentile").append(Math.floor(challenge.challenges[45].percentile * 1000) / 10.0);
        jQuery(".challenge46percentile").append(Math.floor(challenge.challenges[46].percentile * 1000) / 10.0);
        jQuery(".challenge47percentile").append(Math.floor(challenge.challenges[47].percentile * 1000) / 10.0);
        jQuery(".challenge48percentile").append(Math.floor(challenge.challenges[48].percentile * 1000) / 10.0);
        jQuery(".challenge49percentile").append(Math.floor(challenge.challenges[49].percentile * 1000) / 10.0);
        jQuery(".challenge50percentile").append(Math.floor(challenge.challenges[50].percentile * 1000) / 10.0);
        jQuery(".challenge51percentile").append(Math.floor(challenge.challenges[51].percentile * 1000) / 10.0);
        jQuery(".challenge52percentile").append(Math.floor(challenge.challenges[52].percentile * 1000) / 10.0);
        jQuery(".challenge53percentile").append(Math.floor(challenge.challenges[53].percentile * 1000) / 10.0);
        jQuery(".challenge54percentile").append(Math.floor(challenge.challenges[54].percentile * 1000) / 10.0);
        jQuery(".challenge55percentile").append(Math.floor(challenge.challenges[55].percentile * 1000) / 10.0);
        jQuery(".challenge56percentile").append(Math.floor(challenge.challenges[56].percentile * 1000) / 10.0);
        jQuery(".challenge57percentile").append(Math.floor(challenge.challenges[57].percentile * 1000) / 10.0);
        jQuery(".challenge58percentile").append(Math.floor(challenge.challenges[58].percentile * 1000) / 10.0);
        jQuery(".challenge59percentile").append(Math.floor(challenge.challenges[59].percentile * 1000) / 10.0);
        jQuery(".challenge60percentile").append(Math.floor(challenge.challenges[60].percentile * 1000) / 10.0);
        jQuery(".challenge61percentile").append(Math.floor(challenge.challenges[61].percentile * 1000) / 10.0);
        jQuery(".challenge62percentile").append(Math.floor(challenge.challenges[62].percentile * 1000) / 10.0);
        jQuery(".challenge63percentile").append(Math.floor(challenge.challenges[63].percentile * 1000) / 10.0);
        jQuery(".challenge64percentile").append(Math.floor(challenge.challenges[64].percentile * 1000) / 10.0);
        jQuery(".challenge65percentile").append(Math.floor(challenge.challenges[65].percentile * 1000) / 10.0);
        jQuery(".challenge66percentile").append(Math.floor(challenge.challenges[66].percentile * 1000) / 10.0);
        jQuery(".challenge67percentile").append(Math.floor(challenge.challenges[67].percentile * 1000) / 10.0);
        jQuery(".challenge68percentile").append(Math.floor(challenge.challenges[68].percentile * 1000) / 10.0);
        jQuery(".challenge69percentile").append(Math.floor(challenge.challenges[69].percentile * 1000) / 10.0);
        jQuery(".challenge70percentile").append(Math.floor(challenge.challenges[70].percentile * 1000) / 10.0);
        jQuery(".challenge71percentile").append(Math.floor(challenge.challenges[71].percentile * 1000) / 10.0);
        jQuery(".challenge72percentile").append(Math.floor(challenge.challenges[72].percentile * 1000) / 10.0);
        jQuery(".challenge73percentile").append(Math.floor(challenge.challenges[73].percentile * 1000) / 10.0);
        jQuery(".challenge74percentile").append(Math.floor(challenge.challenges[74].percentile * 1000) / 10.0);
        jQuery(".challenge75percentile").append(Math.floor(challenge.challenges[75].percentile * 1000) / 10.0);
        jQuery(".challenge76percentile").append(Math.floor(challenge.challenges[76].percentile * 1000) / 10.0);
        jQuery(".challenge77percentile").append(Math.floor(challenge.challenges[77].percentile * 1000) / 10.0);
        jQuery(".challenge78percentile").append(Math.floor(challenge.challenges[78].percentile * 1000) / 10.0);
        jQuery(".challenge79percentile").append(Math.floor(challenge.challenges[79].percentile * 1000) / 10.0);
        jQuery(".challenge80percentile").append(Math.floor(challenge.challenges[80].percentile * 1000) / 10.0);
        jQuery(".challenge81percentile").append(Math.floor(challenge.challenges[81].percentile * 1000) / 10.0);
        jQuery(".challenge82percentile").append(Math.floor(challenge.challenges[82].percentile * 1000) / 10.0);
        jQuery(".challenge83percentile").append(Math.floor(challenge.challenges[83].percentile * 1000) / 10.0);
        jQuery(".challenge84percentile").append(Math.floor(challenge.challenges[84].percentile * 1000) / 10.0);
        jQuery(".challenge85percentile").append(Math.floor(challenge.challenges[85].percentile * 1000) / 10.0);
        jQuery(".challenge86percentile").append(Math.floor(challenge.challenges[86].percentile * 1000) / 10.0);
        jQuery(".challenge87percentile").append(Math.floor(challenge.challenges[87].percentile * 1000) / 10.0);
        jQuery(".challenge88percentile").append(Math.floor(challenge.challenges[88].percentile * 1000) / 10.0);
        jQuery(".challenge89percentile").append(Math.floor(challenge.challenges[89].percentile * 1000) / 10.0);
        jQuery(".challenge90percentile").append(Math.floor(challenge.challenges[90].percentile * 1000) / 10.0);
        jQuery(".challenge91percentile").append(Math.floor(challenge.challenges[91].percentile * 1000) / 10.0);
        jQuery(".challenge92percentile").append(Math.floor(challenge.challenges[92].percentile * 1000) / 10.0);
        jQuery(".challenge93percentile").append(Math.floor(challenge.challenges[93].percentile * 1000) / 10.0);
        jQuery(".challenge94percentile").append(Math.floor(challenge.challenges[94].percentile * 1000) / 10.0);
        jQuery(".challenge95percentile").append(Math.floor(challenge.challenges[95].percentile * 1000) / 10.0);
        jQuery(".challenge96percentile").append(Math.floor(challenge.challenges[96].percentile * 1000) / 10.0);
        jQuery(".challenge97percentile").append(Math.floor(challenge.challenges[97].percentile * 1000) / 10.0);
        jQuery(".challenge98percentile").append(Math.floor(challenge.challenges[98].percentile * 1000) / 10.0);
        jQuery(".challenge99percentile").append(Math.floor(challenge.challenges[99].percentile * 1000) / 10.0);
        jQuery(".challenge100percentile").append(Math.floor(challenge.challenges[100].percentile * 1000) / 10.0);
        jQuery(".challenge101percentile").append(Math.floor(challenge.challenges[101].percentile * 1000) / 10.0);
        jQuery(".challenge102percentile").append(Math.floor(challenge.challenges[102].percentile * 1000) / 10.0);
        jQuery(".challenge103percentile").append(Math.floor(challenge.challenges[103].percentile * 1000) / 10.0);
        jQuery(".challenge104percentile").append(Math.floor(challenge.challenges[104].percentile * 1000) / 10.0);
        jQuery(".challenge105percentile").append(Math.floor(challenge.challenges[105].percentile * 1000) / 10.0);
        jQuery(".challenge106percentile").append(Math.floor(challenge.challenges[106].percentile * 1000) / 10.0);
        jQuery(".challenge107percentile").append(Math.floor(challenge.challenges[107].percentile * 1000) / 10.0);
        jQuery(".challenge108percentile").append(Math.floor(challenge.challenges[108].percentile * 1000) / 10.0);
        jQuery(".challenge109percentile").append(Math.floor(challenge.challenges[109].percentile * 1000) / 10.0);
        jQuery(".challenge110percentile").append(Math.floor(challenge.challenges[110].percentile * 1000) / 10.0);
        jQuery(".challenge111percentile").append(Math.floor(challenge.challenges[111].percentile * 1000) / 10.0);
        jQuery(".challenge112percentile").append(Math.floor(challenge.challenges[112].percentile * 1000) / 10.0);
        jQuery(".challenge113percentile").append(Math.floor(challenge.challenges[113].percentile * 1000) / 10.0);
        jQuery(".challenge114percentile").append(Math.floor(challenge.challenges[114].percentile * 1000) / 10.0);
        jQuery(".challenge115percentile").append(Math.floor(challenge.challenges[115].percentile * 1000) / 10.0);
        jQuery(".challenge116percentile").append(Math.floor(challenge.challenges[116].percentile * 1000) / 10.0);
        jQuery(".challenge117percentile").append(Math.floor(challenge.challenges[117].percentile * 1000) / 10.0);
        jQuery(".challenge118percentile").append(Math.floor(challenge.challenges[118].percentile * 1000) / 10.0);
        jQuery(".challenge119percentile").append(Math.floor(challenge.challenges[119].percentile * 1000) / 10.0);
        jQuery(".challenge120percentile").append(Math.floor(challenge.challenges[120].percentile * 1000) / 10.0);
        jQuery(".challenge121percentile").append(Math.floor(challenge.challenges[121].percentile * 1000) / 10.0);
        jQuery(".challenge122percentile").append(Math.floor(challenge.challenges[122].percentile * 1000) / 10.0);
        jQuery(".challenge123percentile").append(Math.floor(challenge.challenges[123].percentile * 1000) / 10.0);
        jQuery(".challenge124percentile").append(Math.floor(challenge.challenges[124].percentile * 1000) / 10.0);
        jQuery(".challenge125percentile").append(Math.floor(challenge.challenges[125].percentile * 1000) / 10.0);
        jQuery(".challenge126percentile").append(Math.floor(challenge.challenges[126].percentile * 1000) / 10.0);
        jQuery(".challenge127percentile").append(Math.floor(challenge.challenges[127].percentile * 1000) / 10.0);
        jQuery(".challenge128percentile").append(Math.floor(challenge.challenges[128].percentile * 1000) / 10.0);
        jQuery(".challenge129percentile").append(Math.floor(challenge.challenges[129].percentile * 1000) / 10.0);
        jQuery(".challenge130percentile").append(Math.floor(challenge.challenges[130].percentile * 1000) / 10.0);
        jQuery(".challenge131percentile").append(Math.floor(challenge.challenges[131].percentile * 1000) / 10.0);
        jQuery(".challenge132percentile").append(Math.floor(challenge.challenges[132].percentile * 1000) / 10.0);
        jQuery(".challenge133percentile").append(Math.floor(challenge.challenges[133].percentile * 1000) / 10.0);
        jQuery(".challenge134percentile").append(Math.floor(challenge.challenges[134].percentile * 1000) / 10.0);
        jQuery(".challenge135percentile").append(Math.floor(challenge.challenges[135].percentile * 1000) / 10.0);
        jQuery(".challenge136percentile").append(Math.floor(challenge.challenges[136].percentile * 1000) / 10.0);
        jQuery(".challenge137percentile").append(Math.floor(challenge.challenges[137].percentile * 1000) / 10.0);
        jQuery(".challenge138percentile").append(Math.floor(challenge.challenges[138].percentile * 1000) / 10.0);
        jQuery(".challenge139percentile").append(Math.floor(challenge.challenges[139].percentile * 1000) / 10.0);
        jQuery(".challenge140percentile").append(Math.floor(challenge.challenges[140].percentile * 1000) / 10.0);
        jQuery(".challenge141percentile").append(Math.floor(challenge.challenges[141].percentile * 1000) / 10.0);
        jQuery(".challenge142percentile").append(Math.floor(challenge.challenges[142].percentile * 1000) / 10.0);
        jQuery(".challenge143percentile").append(Math.floor(challenge.challenges[143].percentile * 1000) / 10.0);
        jQuery(".challenge144percentile").append(Math.floor(challenge.challenges[144].percentile * 1000) / 10.0);
        jQuery(".challenge145percentile").append(Math.floor(challenge.challenges[145].percentile * 1000) / 10.0);
        jQuery(".challenge146percentile").append(Math.floor(challenge.challenges[146].percentile * 1000) / 10.0);
        jQuery(".challenge147percentile").append(Math.floor(challenge.challenges[147].percentile * 1000) / 10.0);
        jQuery(".challenge148percentile").append(Math.floor(challenge.challenges[148].percentile * 1000) / 10.0);
        jQuery(".challenge149percentile").append(Math.floor(challenge.challenges[149].percentile * 1000) / 10.0);
        jQuery(".challenge150percentile").append(Math.floor(challenge.challenges[150].percentile * 1000) / 10.0);
        jQuery(".challenge151percentile").append(Math.floor(challenge.challenges[151].percentile * 1000) / 10.0);
        jQuery(".challenge152percentile").append(Math.floor(challenge.challenges[152].percentile * 1000) / 10.0);
        jQuery(".challenge153percentile").append(Math.floor(challenge.challenges[153].percentile * 1000) / 10.0);
        jQuery(".challenge154percentile").append(Math.floor(challenge.challenges[154].percentile * 1000) / 10.0);
        jQuery(".challenge155percentile").append(Math.floor(challenge.challenges[155].percentile * 1000) / 10.0);
        jQuery(".challenge156percentile").append(Math.floor(challenge.challenges[156].percentile * 1000) / 10.0);
        jQuery(".challenge157percentile").append(Math.floor(challenge.challenges[157].percentile * 1000) / 10.0);
        jQuery(".challenge158percentile").append(Math.floor(challenge.challenges[158].percentile * 1000) / 10.0);
        jQuery(".challenge159percentile").append(Math.floor(challenge.challenges[159].percentile * 1000) / 10.0);
        jQuery(".challenge160percentile").append(Math.floor(challenge.challenges[160].percentile * 1000) / 10.0);
        jQuery(".challenge161percentile").append(Math.floor(challenge.challenges[161].percentile * 1000) / 10.0);
        jQuery(".challenge162percentile").append(Math.floor(challenge.challenges[162].percentile * 1000) / 10.0);
        jQuery(".challenge163percentile").append(Math.floor(challenge.challenges[163].percentile * 1000) / 10.0);
        jQuery(".challenge164percentile").append(Math.floor(challenge.challenges[164].percentile * 1000) / 10.0);
        jQuery(".challenge165percentile").append(Math.floor(challenge.challenges[165].percentile * 1000) / 10.0);
        jQuery(".challenge166percentile").append(Math.floor(challenge.challenges[166].percentile * 1000) / 10.0);
        jQuery(".challenge167percentile").append(Math.floor(challenge.challenges[167].percentile * 1000) / 10.0);
        jQuery(".challenge168percentile").append(Math.floor(challenge.challenges[168].percentile * 1000) / 10.0);
        jQuery(".challenge169percentile").append(Math.floor(challenge.challenges[169].percentile * 1000) / 10.0);
        jQuery(".challenge170percentile").append(Math.floor(challenge.challenges[170].percentile * 1000) / 10.0);
        jQuery(".challenge171percentile").append(Math.floor(challenge.challenges[171].percentile * 1000) / 10.0);
        jQuery(".challenge172percentile").append(Math.floor(challenge.challenges[172].percentile * 1000) / 10.0);
        jQuery(".challenge173percentile").append(Math.floor(challenge.challenges[173].percentile * 1000) / 10.0);
        jQuery(".challenge174percentile").append(Math.floor(challenge.challenges[174].percentile * 1000) / 10.0);
        jQuery(".challenge175percentile").append(Math.floor(challenge.challenges[175].percentile * 1000) / 10.0);
        jQuery(".challenge176percentile").append(Math.floor(challenge.challenges[176].percentile * 1000) / 10.0);
        jQuery(".challenge177percentile").append(Math.floor(challenge.challenges[177].percentile * 1000) / 10.0);
        jQuery(".challenge178percentile").append(Math.floor(challenge.challenges[178].percentile * 1000) / 10.0);
        jQuery(".challenge179percentile").append(Math.floor(challenge.challenges[179].percentile * 1000) / 10.0);
        jQuery(".challenge180percentile").append(Math.floor(challenge.challenges[180].percentile * 1000) / 10.0);
        jQuery(".challenge181percentile").append(Math.floor(challenge.challenges[181].percentile * 1000) / 10.0);
        jQuery(".challenge182percentile").append(Math.floor(challenge.challenges[182].percentile * 1000) / 10.0);
        jQuery(".challenge183percentile").append(Math.floor(challenge.challenges[183].percentile * 1000) / 10.0);
        jQuery(".challenge184percentile").append(Math.floor(challenge.challenges[184].percentile * 1000) / 10.0);
        jQuery(".challenge185percentile").append(Math.floor(challenge.challenges[185].percentile * 1000) / 10.0);
        jQuery(".challenge186percentile").append(Math.floor(challenge.challenges[186].percentile * 1000) / 10.0);
        jQuery(".challenge187percentile").append(Math.floor(challenge.challenges[187].percentile * 1000) / 10.0);
        jQuery(".challenge188percentile").append(Math.floor(challenge.challenges[188].percentile * 1000) / 10.0);
        jQuery(".challenge189percentile").append(Math.floor(challenge.challenges[189].percentile * 1000) / 10.0);
        jQuery(".challenge190percentile").append(Math.floor(challenge.challenges[190].percentile * 1000) / 10.0);
        jQuery(".challenge191percentile").append(Math.floor(challenge.challenges[191].percentile * 1000) / 10.0);
        jQuery(".challenge192percentile").append(Math.floor(challenge.challenges[192].percentile * 1000) / 10.0);
        jQuery(".challenge193percentile").append(Math.floor(challenge.challenges[193].percentile * 1000) / 10.0);
        jQuery(".challenge194percentile").append(Math.floor(challenge.challenges[194].percentile * 1000) / 10.0);
        jQuery(".challenge195percentile").append(Math.floor(challenge.challenges[195].percentile * 1000) / 10.0);
        jQuery(".challenge196percentile").append(Math.floor(challenge.challenges[196].percentile * 1000) / 10.0);
        jQuery(".challenge197percentile").append(Math.floor(challenge.challenges[197].percentile * 1000) / 10.0);
        jQuery(".challenge198percentile").append(Math.floor(challenge.challenges[198].percentile * 1000) / 10.0);
        jQuery(".challenge199percentile").append(Math.floor(challenge.challenges[199].percentile * 1000) / 10.0);
        jQuery(".challenge200percentile").append(Math.floor(challenge.challenges[200].percentile * 1000) / 10.0);
        jQuery(".challenge201percentile").append(Math.floor(challenge.challenges[201].percentile * 1000) / 10.0);
        jQuery(".challenge202percentile").append(Math.floor(challenge.challenges[202].percentile * 1000) / 10.0);
        jQuery(".challenge203percentile").append(Math.floor(challenge.challenges[203].percentile * 1000) / 10.0);
        jQuery(".challenge204percentile").append(Math.floor(challenge.challenges[204].percentile * 1000) / 10.0);
        jQuery(".challenge205percentile").append(Math.floor(challenge.challenges[205].percentile * 1000) / 10.0);
        jQuery(".challenge206percentile").append(Math.floor(challenge.challenges[206].percentile * 1000) / 10.0);
        jQuery(".challenge207percentile").append(Math.floor(challenge.challenges[207].percentile * 1000) / 10.0);
        jQuery(".challenge208percentile").append(Math.floor(challenge.challenges[208].percentile * 1000) / 10.0);
        jQuery(".challenge209percentile").append(Math.floor(challenge.challenges[209].percentile * 1000) / 10.0);
        jQuery(".challenge210percentile").append(Math.floor(challenge.challenges[210].percentile * 1000) / 10.0);
        jQuery(".challenge211percentile").append(Math.floor(challenge.challenges[211].percentile * 1000) / 10.0);
        jQuery(".challenge212percentile").append(Math.floor(challenge.challenges[212].percentile * 1000) / 10.0);
        jQuery(".challenge213percentile").append(Math.floor(challenge.challenges[213].percentile * 1000) / 10.0);
        jQuery(".challenge214percentile").append(Math.floor(challenge.challenges[214].percentile * 1000) / 10.0);
        jQuery(".challenge215percentile").append(Math.floor(challenge.challenges[215].percentile * 1000) / 10.0);
        jQuery(".challenge216percentile").append(Math.floor(challenge.challenges[216].percentile * 1000) / 10.0);
        jQuery(".challenge217percentile").append(Math.floor(challenge.challenges[217].percentile * 1000) / 10.0);
        jQuery(".challenge218percentile").append(Math.floor(challenge.challenges[218].percentile * 1000) / 10.0);
        jQuery(".challenge219percentile").append(Math.floor(challenge.challenges[219].percentile * 1000) / 10.0);
        jQuery(".challenge220percentile").append(Math.floor(challenge.challenges[220].percentile * 1000) / 10.0);
        jQuery(".challenge221percentile").append(Math.floor(challenge.challenges[221].percentile * 1000) / 10.0);
        jQuery(".challenge222percentile").append(Math.floor(challenge.challenges[222].percentile * 1000) / 10.0);
        jQuery(".challenge223percentile").append(Math.floor(challenge.challenges[223].percentile * 1000) / 10.0);
        jQuery(".challenge224percentile").append(Math.floor(challenge.challenges[224].percentile * 1000) / 10.0);
        jQuery(".challenge225percentile").append(Math.floor(challenge.challenges[225].percentile * 1000) / 10.0);
        jQuery(".challenge226percentile").append(Math.floor(challenge.challenges[226].percentile * 1000) / 10.0);
        jQuery(".challenge227percentile").append(Math.floor(challenge.challenges[227].percentile * 1000) / 10.0);
        jQuery(".challenge228percentile").append(Math.floor(challenge.challenges[228].percentile * 1000) / 10.0);
        jQuery(".challenge229percentile").append(Math.floor(challenge.challenges[229].percentile * 1000) / 10.0);
        jQuery(".challenge230percentile").append(Math.floor(challenge.challenges[230].percentile * 1000) / 10.0);
        jQuery(".challenge231percentile").append(Math.floor(challenge.challenges[231].percentile * 1000) / 10.0);
        jQuery(".challenge232percentile").append(Math.floor(challenge.challenges[232].percentile * 1000) / 10.0);
        jQuery(".challenge233percentile").append(Math.floor(challenge.challenges[233].percentile * 1000) / 10.0);
        jQuery(".challenge234percentile").append(Math.floor(challenge.challenges[234].percentile * 1000) / 10.0);
        jQuery(".challenge235percentile").append(Math.floor(challenge.challenges[235].percentile * 1000) / 10.0);
        jQuery(".challenge236percentile").append(Math.floor(challenge.challenges[236].percentile * 1000) / 10.0);
        jQuery(".challenge237percentile").append(Math.floor(challenge.challenges[237].percentile * 1000) / 10.0);
        jQuery(".challenge238percentile").append(Math.floor(challenge.challenges[238].percentile * 1000) / 10.0);
        jQuery(".challenge239percentile").append(Math.floor(challenge.challenges[239].percentile * 1000) / 10.0);
        jQuery(".challenge240percentile").append(Math.floor(challenge.challenges[240].percentile * 1000) / 10.0);
        jQuery(".challenge241percentile").append(Math.floor(challenge.challenges[241].percentile * 1000) / 10.0);
        jQuery(".challenge242percentile").append(Math.floor(challenge.challenges[242].percentile * 1000) / 10.0);
        jQuery(".challenge243percentile").append(Math.floor(challenge.challenges[243].percentile * 1000) / 10.0);
        jQuery(".challenge244percentile").append(Math.floor(challenge.challenges[244].percentile * 1000) / 10.0);
        jQuery(".challenge245percentile").append(Math.floor(challenge.challenges[245].percentile * 1000) / 10.0);
        jQuery(".challenge246percentile").append(Math.floor(challenge.challenges[246].percentile * 1000) / 10.0);
        jQuery(".challenge247percentile").append(Math.floor(challenge.challenges[247].percentile * 1000) / 10.0);
        jQuery(".challenge248percentile").append(Math.floor(challenge.challenges[248].percentile * 1000) / 10.0);
        jQuery(".challenge249percentile").append(Math.floor(challenge.challenges[249].percentile * 1000) / 10.0);
        jQuery(".challenge250percentile").append(Math.floor(challenge.challenges[250].percentile * 1000) / 10.0);
        jQuery(".challenge251percentile").append(Math.floor(challenge.challenges[251].percentile * 1000) / 10.0);
        jQuery(".challenge252percentile").append(Math.floor(challenge.challenges[252].percentile * 1000) / 10.0);
        jQuery(".challenge253percentile").append(Math.floor(challenge.challenges[253].percentile * 1000) / 10.0);
        jQuery(".challenge254percentile").append(Math.floor(challenge.challenges[254].percentile * 1000) / 10.0);
        jQuery(".challenge255percentile").append(Math.floor(challenge.challenges[255].percentile * 1000) / 10.0);
        jQuery(".challenge256percentile").append(Math.floor(challenge.challenges[256].percentile * 1000) / 10.0);
        jQuery(".challenge257percentile").append(Math.floor(challenge.challenges[257].percentile * 1000) / 10.0);
    });

    jQuery.getJSON("https://na1.api.riotgames.com/lol/challenges/v1/challenges/config?api_key=" + riotAPIKey,
    function(name){
        jQuery(".challenge0name").append(name[0].localizedNames.en_US.name);
        jQuery(".challenge1name").append(name[1].localizedNames.en_US.name);
        jQuery(".challenge2name").append(name[2].localizedNames.en_US.name);
        jQuery(".challenge3name").append(name[3].localizedNames.en_US.name);
        jQuery(".challenge4name").append(name[4].localizedNames.en_US.name);
        jQuery(".challenge5name").append(name[5].localizedNames.en_US.name);
        jQuery(".challenge6name").append(name[6].localizedNames.en_US.name);
        jQuery(".challenge7name").append(name[7].localizedNames.en_US.name);
        jQuery(".challenge8name").append(name[8].localizedNames.en_US.name);
        jQuery(".challenge9name").append(name[9].localizedNames.en_US.name);
        jQuery(".challenge10name").append(name[10].localizedNames.en_US.name);
        jQuery(".challenge11name").append(name[11].localizedNames.en_US.name);
        jQuery(".challenge12name").append(name[12].localizedNames.en_US.name);
        jQuery(".challenge13name").append(name[13].localizedNames.en_US.name);
        jQuery(".challenge14name").append(name[14].localizedNames.en_US.name);
        jQuery(".challenge15name").append(name[15].localizedNames.en_US.name);
        jQuery(".challenge16name").append(name[16].localizedNames.en_US.name);
        jQuery(".challenge17name").append(name[17].localizedNames.en_US.name);
        jQuery(".challenge18name").append(name[18].localizedNames.en_US.name);
        jQuery(".challenge19name").append(name[19].localizedNames.en_US.name);
        jQuery(".challenge20name").append(name[20].localizedNames.en_US.name);
        jQuery(".challenge21name").append(name[21].localizedNames.en_US.name);
        jQuery(".challenge22name").append(name[22].localizedNames.en_US.name);
        jQuery(".challenge23name").append(name[23].localizedNames.en_US.name);
        jQuery(".challenge24name").append(name[24].localizedNames.en_US.name);
        jQuery(".challenge25name").append(name[25].localizedNames.en_US.name);
        jQuery(".challenge26name").append(name[26].localizedNames.en_US.name);
        jQuery(".challenge27name").append(name[27].localizedNames.en_US.name);
        jQuery(".challenge28name").append(name[28].localizedNames.en_US.name);
        jQuery(".challenge29name").append(name[29].localizedNames.en_US.name);
        jQuery(".challenge30name").append(name[30].localizedNames.en_US.name);
        jQuery(".challenge31name").append(name[31].localizedNames.en_US.name);
        jQuery(".challenge32name").append(name[32].localizedNames.en_US.name);
        jQuery(".challenge33name").append(name[33].localizedNames.en_US.name);
        jQuery(".challenge34name").append(name[34].localizedNames.en_US.name);
        jQuery(".challenge35name").append(name[35].localizedNames.en_US.name);
        jQuery(".challenge36name").append(name[36].localizedNames.en_US.name);
        jQuery(".challenge37name").append(name[37].localizedNames.en_US.name);
        jQuery(".challenge38name").append(name[38].localizedNames.en_US.name);
        jQuery(".challenge39name").append(name[39].localizedNames.en_US.name);
        jQuery(".challenge40name").append(name[40].localizedNames.en_US.name);
        jQuery(".challenge41name").append(name[41].localizedNames.en_US.name);
        jQuery(".challenge42name").append(name[42].localizedNames.en_US.name);
        jQuery(".challenge43name").append(name[43].localizedNames.en_US.name);
        jQuery(".challenge44name").append(name[44].localizedNames.en_US.name);
        jQuery(".challenge45name").append(name[45].localizedNames.en_US.name);
        jQuery(".challenge46name").append(name[46].localizedNames.en_US.name);
        jQuery(".challenge47name").append(name[47].localizedNames.en_US.name);
        jQuery(".challenge48name").append(name[48].localizedNames.en_US.name);
        jQuery(".challenge49name").append(name[49].localizedNames.en_US.name);
        jQuery(".challenge50name").append(name[50].localizedNames.en_US.name);
        jQuery(".challenge51name").append(name[51].localizedNames.en_US.name);
        jQuery(".challenge52name").append(name[52].localizedNames.en_US.name);
        jQuery(".challenge53name").append(name[53].localizedNames.en_US.name);
        jQuery(".challenge54name").append(name[54].localizedNames.en_US.name);
        jQuery(".challenge55name").append(name[55].localizedNames.en_US.name);
        jQuery(".challenge56name").append(name[56].localizedNames.en_US.name);
        jQuery(".challenge57name").append(name[57].localizedNames.en_US.name);
        jQuery(".challenge58name").append(name[58].localizedNames.en_US.name);
        jQuery(".challenge59name").append(name[59].localizedNames.en_US.name);
        jQuery(".challenge60name").append(name[60].localizedNames.en_US.name);
        jQuery(".challenge61name").append(name[61].localizedNames.en_US.name);
        jQuery(".challenge62name").append(name[62].localizedNames.en_US.name);
        jQuery(".challenge63name").append(name[63].localizedNames.en_US.name);
        jQuery(".challenge64name").append(name[64].localizedNames.en_US.name);
        jQuery(".challenge65name").append(name[65].localizedNames.en_US.name);
        jQuery(".challenge66name").append(name[66].localizedNames.en_US.name);
        jQuery(".challenge67name").append(name[67].localizedNames.en_US.name);
        jQuery(".challenge68name").append(name[68].localizedNames.en_US.name);
        jQuery(".challenge69name").append(name[69].localizedNames.en_US.name);
        jQuery(".challenge70name").append(name[70].localizedNames.en_US.name);
        jQuery(".challenge71name").append(name[71].localizedNames.en_US.name);
        jQuery(".challenge72name").append(name[72].localizedNames.en_US.name);
        jQuery(".challenge73name").append(name[73].localizedNames.en_US.name);
        jQuery(".challenge74name").append(name[74].localizedNames.en_US.name);
        jQuery(".challenge75name").append(name[75].localizedNames.en_US.name);
        jQuery(".challenge76name").append(name[76].localizedNames.en_US.name);
        jQuery(".challenge77name").append(name[77].localizedNames.en_US.name);
        jQuery(".challenge78name").append(name[78].localizedNames.en_US.name);
        jQuery(".challenge79name").append(name[79].localizedNames.en_US.name);
        jQuery(".challenge80name").append(name[80].localizedNames.en_US.name);
        jQuery(".challenge81name").append(name[81].localizedNames.en_US.name);
        jQuery(".challenge82name").append(name[82].localizedNames.en_US.name);
        jQuery(".challenge83name").append(name[83].localizedNames.en_US.name);
        jQuery(".challenge84name").append(name[84].localizedNames.en_US.name);
        jQuery(".challenge85name").append(name[85].localizedNames.en_US.name);
        jQuery(".challenge86name").append(name[86].localizedNames.en_US.name);
        jQuery(".challenge87name").append(name[87].localizedNames.en_US.name);
        jQuery(".challenge88name").append(name[88].localizedNames.en_US.name);
        jQuery(".challenge89name").append(name[89].localizedNames.en_US.name);
        jQuery(".challenge90name").append(name[90].localizedNames.en_US.name);
        jQuery(".challenge91name").append(name[91].localizedNames.en_US.name);
        jQuery(".challenge92name").append(name[92].localizedNames.en_US.name);
        jQuery(".challenge93name").append(name[93].localizedNames.en_US.name);
        jQuery(".challenge94name").append(name[94].localizedNames.en_US.name);
        jQuery(".challenge95name").append(name[95].localizedNames.en_US.name);
        jQuery(".challenge96name").append(name[96].localizedNames.en_US.name);
        jQuery(".challenge97name").append(name[97].localizedNames.en_US.name);
        jQuery(".challenge98name").append(name[98].localizedNames.en_US.name);
        jQuery(".challenge99name").append(name[99].localizedNames.en_US.name);
        jQuery(".challenge100name").append(name[100].localizedNames.en_US.name);
        jQuery(".challenge101name").append(name[101].localizedNames.en_US.name);
        jQuery(".challenge102name").append(name[102].localizedNames.en_US.name);
        jQuery(".challenge103name").append(name[103].localizedNames.en_US.name);
        jQuery(".challenge104name").append(name[104].localizedNames.en_US.name);
        jQuery(".challenge105name").append(name[105].localizedNames.en_US.name);
        jQuery(".challenge106name").append(name[106].localizedNames.en_US.name);
        jQuery(".challenge107name").append(name[107].localizedNames.en_US.name);
        jQuery(".challenge108name").append(name[108].localizedNames.en_US.name);
        jQuery(".challenge109name").append(name[109].localizedNames.en_US.name);
        jQuery(".challenge110name").append(name[110].localizedNames.en_US.name);
        jQuery(".challenge111name").append(name[111].localizedNames.en_US.name);
        jQuery(".challenge112name").append(name[112].localizedNames.en_US.name);
        jQuery(".challenge113name").append(name[113].localizedNames.en_US.name);
        jQuery(".challenge114name").append(name[114].localizedNames.en_US.name);
        jQuery(".challenge115name").append(name[115].localizedNames.en_US.name);
        jQuery(".challenge116name").append(name[116].localizedNames.en_US.name);
        jQuery(".challenge117name").append(name[117].localizedNames.en_US.name);
        jQuery(".challenge118name").append(name[118].localizedNames.en_US.name);
        jQuery(".challenge119name").append(name[119].localizedNames.en_US.name);
        jQuery(".challenge120name").append(name[120].localizedNames.en_US.name);
        jQuery(".challenge121name").append(name[121].localizedNames.en_US.name);
        jQuery(".challenge122name").append(name[122].localizedNames.en_US.name);
        jQuery(".challenge123name").append(name[123].localizedNames.en_US.name);
        jQuery(".challenge124name").append(name[124].localizedNames.en_US.name);
        jQuery(".challenge125name").append(name[125].localizedNames.en_US.name);
        jQuery(".challenge126name").append(name[126].localizedNames.en_US.name);
        jQuery(".challenge127name").append(name[127].localizedNames.en_US.name);
        jQuery(".challenge128name").append(name[128].localizedNames.en_US.name);
        jQuery(".challenge129name").append(name[129].localizedNames.en_US.name);
        jQuery(".challenge130name").append(name[130].localizedNames.en_US.name);
        jQuery(".challenge131name").append(name[131].localizedNames.en_US.name);
        jQuery(".challenge132name").append(name[132].localizedNames.en_US.name);
        jQuery(".challenge133name").append(name[133].localizedNames.en_US.name);
        jQuery(".challenge134name").append(name[134].localizedNames.en_US.name);
        jQuery(".challenge135name").append(name[135].localizedNames.en_US.name);
        jQuery(".challenge136name").append(name[136].localizedNames.en_US.name);
        jQuery(".challenge137name").append(name[137].localizedNames.en_US.name);
        jQuery(".challenge138name").append(name[138].localizedNames.en_US.name);
        jQuery(".challenge139name").append(name[139].localizedNames.en_US.name);
        jQuery(".challenge140name").append(name[140].localizedNames.en_US.name);
        jQuery(".challenge141name").append(name[141].localizedNames.en_US.name);
        jQuery(".challenge142name").append(name[142].localizedNames.en_US.name);
        jQuery(".challenge143name").append(name[143].localizedNames.en_US.name);
        jQuery(".challenge144name").append(name[144].localizedNames.en_US.name);
        jQuery(".challenge145name").append(name[145].localizedNames.en_US.name);
        jQuery(".challenge146name").append(name[146].localizedNames.en_US.name);
        jQuery(".challenge147name").append(name[147].localizedNames.en_US.name);
        jQuery(".challenge148name").append(name[148].localizedNames.en_US.name);
        jQuery(".challenge149name").append(name[149].localizedNames.en_US.name);
        jQuery(".challenge150name").append(name[150].localizedNames.en_US.name);
        jQuery(".challenge151name").append(name[151].localizedNames.en_US.name);
        jQuery(".challenge152name").append(name[152].localizedNames.en_US.name);
        jQuery(".challenge153name").append(name[153].localizedNames.en_US.name);
        jQuery(".challenge154name").append(name[154].localizedNames.en_US.name);
        jQuery(".challenge155name").append(name[155].localizedNames.en_US.name);
        jQuery(".challenge156name").append(name[156].localizedNames.en_US.name);
        jQuery(".challenge157name").append(name[157].localizedNames.en_US.name);
        jQuery(".challenge158name").append(name[158].localizedNames.en_US.name);
        jQuery(".challenge159name").append(name[159].localizedNames.en_US.name);
        jQuery(".challenge160name").append(name[160].localizedNames.en_US.name);
        jQuery(".challenge161name").append(name[161].localizedNames.en_US.name);
        jQuery(".challenge162name").append(name[162].localizedNames.en_US.name);
        jQuery(".challenge163name").append(name[163].localizedNames.en_US.name);
        jQuery(".challenge164name").append(name[164].localizedNames.en_US.name);
        jQuery(".challenge165name").append(name[165].localizedNames.en_US.name);
        jQuery(".challenge166name").append(name[166].localizedNames.en_US.name);
        jQuery(".challenge167name").append(name[167].localizedNames.en_US.name);
        jQuery(".challenge168name").append(name[168].localizedNames.en_US.name);
        jQuery(".challenge169name").append(name[169].localizedNames.en_US.name);
        jQuery(".challenge170name").append(name[170].localizedNames.en_US.name);
        jQuery(".challenge171name").append(name[171].localizedNames.en_US.name);
        jQuery(".challenge172name").append(name[172].localizedNames.en_US.name);
        jQuery(".challenge173name").append(name[173].localizedNames.en_US.name);
        jQuery(".challenge174name").append(name[174].localizedNames.en_US.name);
        jQuery(".challenge175name").append(name[175].localizedNames.en_US.name);
        jQuery(".challenge176name").append(name[176].localizedNames.en_US.name);
        jQuery(".challenge177name").append(name[177].localizedNames.en_US.name);
        jQuery(".challenge178name").append(name[178].localizedNames.en_US.name);
        jQuery(".challenge179name").append(name[179].localizedNames.en_US.name);
        jQuery(".challenge180name").append(name[180].localizedNames.en_US.name);
        jQuery(".challenge181name").append(name[181].localizedNames.en_US.name);
        jQuery(".challenge182name").append(name[182].localizedNames.en_US.name);
        jQuery(".challenge183name").append(name[183].localizedNames.en_US.name);
        jQuery(".challenge184name").append(name[184].localizedNames.en_US.name);
        jQuery(".challenge185name").append(name[185].localizedNames.en_US.name);
        jQuery(".challenge186name").append(name[186].localizedNames.en_US.name);
        jQuery(".challenge187name").append(name[187].localizedNames.en_US.name);
        jQuery(".challenge188name").append(name[188].localizedNames.en_US.name);
        jQuery(".challenge189name").append(name[189].localizedNames.en_US.name);
        jQuery(".challenge190name").append(name[190].localizedNames.en_US.name);
        jQuery(".challenge191name").append(name[191].localizedNames.en_US.name);
        jQuery(".challenge192name").append(name[192].localizedNames.en_US.name);
        jQuery(".challenge193name").append(name[193].localizedNames.en_US.name);
        jQuery(".challenge194name").append(name[194].localizedNames.en_US.name);
        jQuery(".challenge195name").append(name[195].localizedNames.en_US.name);
        jQuery(".challenge196name").append(name[196].localizedNames.en_US.name);
        jQuery(".challenge197name").append(name[197].localizedNames.en_US.name);
        jQuery(".challenge198name").append(name[198].localizedNames.en_US.name);
        jQuery(".challenge199name").append(name[199].localizedNames.en_US.name);
        jQuery(".challenge200name").append(name[200].localizedNames.en_US.name);
        jQuery(".challenge201name").append(name[201].localizedNames.en_US.name);
        jQuery(".challenge202name").append(name[202].localizedNames.en_US.name);
        jQuery(".challenge203name").append(name[203].localizedNames.en_US.name);
        jQuery(".challenge204name").append(name[204].localizedNames.en_US.name);
        jQuery(".challenge205name").append(name[205].localizedNames.en_US.name);
        jQuery(".challenge206name").append(name[206].localizedNames.en_US.name);
        jQuery(".challenge207name").append(name[207].localizedNames.en_US.name);
        jQuery(".challenge208name").append(name[208].localizedNames.en_US.name);
        jQuery(".challenge209name").append(name[209].localizedNames.en_US.name);
        jQuery(".challenge210name").append(name[210].localizedNames.en_US.name);
        jQuery(".challenge211name").append(name[211].localizedNames.en_US.name);
        jQuery(".challenge212name").append(name[212].localizedNames.en_US.name);
        jQuery(".challenge213name").append(name[213].localizedNames.en_US.name);
        jQuery(".challenge214name").append(name[214].localizedNames.en_US.name);
        jQuery(".challenge215name").append(name[215].localizedNames.en_US.name);
        jQuery(".challenge216name").append(name[216].localizedNames.en_US.name);
        jQuery(".challenge217name").append(name[217].localizedNames.en_US.name);
        jQuery(".challenge218name").append(name[218].localizedNames.en_US.name);
        jQuery(".challenge219name").append(name[219].localizedNames.en_US.name);
        jQuery(".challenge220name").append(name[220].localizedNames.en_US.name);
        jQuery(".challenge221name").append(name[221].localizedNames.en_US.name);
        jQuery(".challenge222name").append(name[222].localizedNames.en_US.name);
        jQuery(".challenge223name").append(name[223].localizedNames.en_US.name);
        jQuery(".challenge224name").append(name[224].localizedNames.en_US.name);
        jQuery(".challenge225name").append(name[225].localizedNames.en_US.name);
        jQuery(".challenge226name").append(name[226].localizedNames.en_US.name);
        jQuery(".challenge227name").append(name[227].localizedNames.en_US.name);
        jQuery(".challenge228name").append(name[228].localizedNames.en_US.name);
        jQuery(".challenge229name").append(name[229].localizedNames.en_US.name);
        jQuery(".challenge230name").append(name[230].localizedNames.en_US.name);
        jQuery(".challenge231name").append(name[231].localizedNames.en_US.name);
        jQuery(".challenge232name").append(name[232].localizedNames.en_US.name);
        jQuery(".challenge233name").append(name[233].localizedNames.en_US.name);
        jQuery(".challenge234name").append(name[234].localizedNames.en_US.name);
        jQuery(".challenge235name").append(name[235].localizedNames.en_US.name);
        jQuery(".challenge236name").append(name[236].localizedNames.en_US.name);
        jQuery(".challenge237name").append(name[237].localizedNames.en_US.name);
        jQuery(".challenge238name").append(name[238].localizedNames.en_US.name);
        jQuery(".challenge239name").append(name[239].localizedNames.en_US.name);
        jQuery(".challenge240name").append(name[240].localizedNames.en_US.name);
        jQuery(".challenge241name").append(name[241].localizedNames.en_US.name);
        jQuery(".challenge242name").append(name[242].localizedNames.en_US.name);
        jQuery(".challenge243name").append(name[243].localizedNames.en_US.name);
        jQuery(".challenge244name").append(name[244].localizedNames.en_US.name);
        jQuery(".challenge245name").append(name[245].localizedNames.en_US.name);
        jQuery(".challenge246name").append(name[246].localizedNames.en_US.name);
        jQuery(".challenge247name").append(name[247].localizedNames.en_US.name);
        jQuery(".challenge248name").append(name[248].localizedNames.en_US.name);
        jQuery(".challenge249name").append(name[249].localizedNames.en_US.name);
        jQuery(".challenge250name").append(name[250].localizedNames.en_US.name);
        jQuery(".challenge251name").append(name[251].localizedNames.en_US.name);
        jQuery(".challenge252name").append(name[252].localizedNames.en_US.name);
        jQuery(".challenge253name").append(name[253].localizedNames.en_US.name);
        jQuery(".challenge254name").append(name[254].localizedNames.en_US.name);
        jQuery(".challenge255name").append(name[255].localizedNames.en_US.name);
        jQuery(".challenge256name").append(name[256].localizedNames.en_US.name);
        jQuery(".challenge257name").append(name[257].localizedNames.en_US.name);
        
    
    });

    

    jQuery(".name").append(name);
    jQuery(".puuid").append(summonerPUUID);
});


console.log("hello");